---
apiVersion: v1
kind: Service
metadata:
  name: eth-devnet
  labels:
    app: eth-devnet
spec:
  ports:
    - port: 8545
      name: rpc
      protocol: TCP
  clusterIP: None
  selector:
    app: eth-devnet
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eth-devnet
spec:
  selector:
    matchLabels:
      app: eth-devnet
  serviceName: eth-devnet
  replicas: 1
  template:
    metadata:
      labels:
        app: eth-devnet
    spec:
      terminationGracePeriodSeconds: 1
      containers:
        - name: geth-node
          image: eth-node
          command:
            - geth
            - --datadir=/home/data
            - --nodiscover
            - --syncmode=full
            - --nodekey=/home/files/priv.key
            - --port=30313
            - --http
            - --http.addr=0.0.0.0
            - --http.vhosts=*
            - --http.corsdomain=*
            - --http.port=8545
            - --http.api=db,eth,net,web3,admin,personal,miner,signer:insecure_unlock_protect
            - --networkid=1
            - --unlock=0
            - --password=/home/files/password
            - --mine
            - --allow-insecure-unlock
            - --ws
            - --ws.port=8545
            - --ws.addr=0.0.0.0
            - --ws.origins=*
            - --ws.api=eth,net,web3
          ports:
            - containerPort: 8545
              name: rpc
              protocol: TCP
            - containerPort: 8545
              name: ws
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: rpc
        - name: tests
          image: eth-node
          stdin: true
          command:
            - /bin/sh
            - -c
            - "npm run migrate && npm run deploy-relayers-evm1 && nc -lkn 2000"
          readinessProbe:
            periodSeconds: 1
            failureThreshold: 300
            initialDelaySeconds: 90
            tcpSocket:
              port: 2000
        # - name: mine
        #   image: eth-node
        #   command:
        #     - /bin/sh
        #     - -c
        #     - "npx truffle exec mine.js"
---

